name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # 启用缓存（可选，但需要 pnpm-lock.yaml 存在）
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # ✅ 关键：确保 pnpm 被安装
      - name: Install pnpm
        run: |
          if ! command -v pnpm; then
            echo "pnpm not found, installing..."
            npm install -g pnpm
          fi
          echo "pnpm version: $(pnpm --version)"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist