name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'  # 关键：这会触发 pnpm 的自动安装 + 依赖缓存
          cache-dependency-path: pnpm-lock.yaml

      # ✅ 显式检查 pnpm 是否存在（调试用，可选）
      - name: Check pnpm
        run: |
          which pnpm
          pnpm --version || echo "pnpm not found!"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist